Feature/news search
jstbrng/uNewsApp pull request #4
Opened 2020-11-05 10:43 UTC by Kola14

Added news search screen with placeholder buttons for tags and time selection with their own popup menus. Updated string list and menus

2020-11-08 17:44 UTC, SomethingBringer commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +        btn_select_time.setOnClickListener {
Здесь и еще в нескольких местах ты для нейминга используешь snake case стиль. В нем самом нет ничего плохого, но по стандартной конвенции следует пользоваться camel case стилем написания.
Это желательно поправить. Во всем остальном - все норм

2020-11-20 06:43 UTC, konovalov-k commented
@Kola14 Слишком большой PR в 500 строк, сложно проверять. Коммиты однотипно названы. Из них должно быть понятно о вносимых изменениях.

2020-11-20 07:01 UTC, konovalov-k requested changes

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/java/com/example/android/unewsapp/ui/MainActivity.kt
> +import android.annotation.SuppressLint
Странно делать импорты, которые не используются ниже

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +    lateinit var viewModel: NewsSearchViewModel
Я не любить lateinit var , мб тут by lazy{} @SomethingBringer ?

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +        (activity?.applicationContext as MyApplication).appComponent.inject(this)
Есть requireActivity() которое null не возвращает.

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +        return inflater.inflate(R.layout.fragment_news_search, container, false)
Можно R.layout.fragment_news_search вынести в конструктор Fragment(R....). @SomethingBringer У меня просто в проектах так, мб не ошибка.

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +        btnSelectTags.setOnClickListener {
Все onLickListener вынести в отдельный метод initOnClickLislteners()

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +                item.isChecked = !item.isChecked
использовать у Item .run{} и в ней накидать все эти методы для него

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +            fun onPrepareOptionsMenu(menu: Menu) {
Не оченькогда внутри лямбы объявление функции @SomethingBringer норм?

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +        newsRecycler.apply {
apply не используется никак, можно убрать

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchViewModel.kt
> +    sealed class State {
объявдение класса внутри viewmodel это норм? @SomethingBringer

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/res/layout/content_main.xml
> +        app:navGraph="@navigation/nav_graph"
Какие-то левые переносы строк

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/res/layout/fragment_news_search.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
А зачем Cosntraint в Constraint?

2020-11-20 07:01 UTC, k-konovalov commented on app/src/main/res/navigation/nav_graph.xml
> +        android:label="Search"
Label не в ресурсах

2020-11-20 07:01 UTC, konovalov-k commented on app/src/main/res/values/strings.xml
> +    <string name="corona"> Коронавирус </string>
А пробелы в начале \ конец зачем?

2020-11-20 07:08 UTC, SomethingBringer commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +    lateinit var viewModel: NewsSearchViewModel
Если несколько запариться, можно сделать лучше именно для viewModel, но это не так тривиально
С Inject иначе и не сделать, насколько мне известно

2020-11-20 07:10 UTC, SomethingBringer commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +        return inflater.inflate(R.layout.fragment_news_search, container, false)
Не ошибка
Делать можно разными способами
Если делать через view binding - этот метод был бы необходимым

2020-11-20 07:29 UTC, SomethingBringer commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchViewModel.kt
> +    sealed class State {
Я не вижу здесь проблемы.
Семантически возможно логичнее класс состояния перенести во фрагмент, если считать его сущностью отображения.
С другой стороны эта сущность связана с работой бизнес логики, а во фрагменте по хорошему не должно быть ничего, кроме отображения.
Думаю возможны оба варианта.

2020-11-20 08:54 UTC, SomethingBringer commented on app/src/main/res/layout/content_main.xml
> +        app:navGraph="@navigation/nav_graph"
Не принципиально

2020-11-20 08:59 UTC, SomethingBringer commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +        newsRecycler.apply {
Не принципиально

2020-11-20 09:02 UTC, SomethingBringer commented on app/src/main/res/layout/fragment_news_search.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Это готовый блок верстки, которым я поделился.
Его удобно реализовать в Constraint разметке.
Если бы родительским лайаутом был бы иной - было бы больше смысла, согласен. Но вопрос в удобстве.

2020-11-20 09:06 UTC, SomethingBringer commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +            fun onPrepareOptionsMenu(menu: Menu) {
Да, лучше вынести

2020-11-20 09:09 UTC, SomethingBringer commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/search/NewsSearchFragment.kt
> +                item.isChecked = !item.isChecked
Не принципиально

2020-11-21 09:40 UTC, SomethingBringer approved these changes

2020-11-21 10:51 UTC, konovalov-k approved these changes

2020-11-21 10:53 UTC, merged