Конвертер валют
jstbrng/uNewsApp pull request #5
Opened 2020-11-20 09:23 UTC by SomethingBringer

2020-11-20 21:15 UTC, konovalov-k commented on app/src/main/java/com/example/android/unewsapp/remote/HelperFunctions.kt
>      if (errorBody != null) {
Можно элвисом жи

2020-11-20 21:16 UTC, konovalov-k commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/converter/ConverterFragment.kt
> +        return inflater.inflate(R.layout.fragment_converter, container, false)
Че  так люббишь плодитьб лиший код в создании)))

2020-11-20 21:19 UTC, konovalov-k commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/converter/ConverterViewModel.kt
> +            } else if (error != null) {
хз почему не люблю проверки в ифе на нулл

2020-11-20 21:20 UTC, konovalov-k commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/converter/ConverterViewModel.kt
> +        pairsLiveData.observeForever {
обсерв потом снимаешь?

2020-11-20 21:21 UTC, konovalov-k commented on app/src/main/res/layout/fragment_converter.xml
> +    <com.google.android.material.appbar.AppBarLayout
Чет этот тулбар везде. А че не в активити прост?

2020-11-20 21:21 UTC, konovalov-k commented on app/src/main/res/layout/item_currency.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Констрейнт не айс в итема, - производительность

2020-11-20 21:23 UTC, konovalov-k requested changes
типа ком

2020-11-21 07:40 UTC, SomethingBringer commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/converter/ConverterFragment.kt
> +        return inflater.inflate(R.layout.fragment_converter, container, false)
Код генерирует навигационный граф
Можно в отдельном пуле избавиться от подобного через базовый класс - в этом пуле решалась задача добавить фичу, а не отрефакторить код

2020-11-21 07:44 UTC, SomethingBringer commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/converter/ConverterViewModel.kt
> +            } else if (error != null) {
Иф - условная конструкция, управляющая исполнением
Можно заменить на let - снизиться читаемость, нарушится логика.
Если заменить проверку ошибки на let, то может произойти отлов "пустой" ошибки, даже когда data в запросе пришла корректно, но на сервере что-то пошло не так и была получена такая ситуация.
Если есть синтаксический сахар - не значит, что его нужно использовать везде

2020-11-21 07:46 UTC, SomethingBringer commented on app/src/main/java/com/example/android/unewsapp/remote/HelperFunctions.kt
>      if (errorBody != null) {
Синтаксический сахар
Смысловой и функциональной нагрузки в этом нет

2020-11-21 08:21 UTC, SomethingBringer commented on app/src/main/java/com/example/android/unewsapp/ui/fragments/converter/ConverterViewModel.kt
> +        pairsLiveData.observeForever {
Нет, в коде же все видно

2020-11-21 08:21 UTC, SomethingBringer commented on app/src/main/res/layout/fragment_converter.xml
> +    <com.google.android.material.appbar.AppBarLayout
Не понял вопроса

2020-11-22 13:37 UTC, merged